### PR TITLE
Adding PDF/SVG files of manual of style, logos, timeline, icons, etc

### PR DESCRIPTION
**Pull request by andreslucena**
#### :tophat: User Story

There are a few related separated files that should be on this repository, regarding the Decidim image. 
Everyday there is an internal user asking for the decidim logo for instance. 

#### :clipboard: Related documentation

None

#### :dart: Acceptance criteria

There should be a section with all the static files: PDF/SVG files of manual of style, logos, timeline, icons

#### :pushpin: Related issues

None

### CODE REVIEW

**Comment by josepjaume** [comment]
Please, use the PR template description: https://github.com/AjuntamentdeBarcelona/decidim-design/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by andreslucena** [comment]
Oh, i didn't see the PR template. Now it's completed.

**Comment by josepjaume** [comment]
I'm unsure on wether we should include provisional material (like the logo proposals) or not. I personally prefer to keep it as clean as possible, with the latest versions. What do you think @htmlboy?

**Comment by htmlboy** [comment]
@josepjaume clean as possible sounds good to me 👍

**Pull request merged**
